app = "sistema-recaudaciones"
primary_region = "bog"

[http_service]
auto_start_machines = true
auto_stop_machines = false
force_https = true
internal_port = 5_000
min_machines_running = 1
processes = [ "app" ]

[[vm]]
cpu_kind = "shared"
cpus = 1
memory_mb = 1_024